
from genEDA import *



class MIMXRT1062(U):
    def __init__(self,refid) -> None:
        U.__init__(self,refid)
        self.name = "iMXRT1062"
        self.type = "MCU"
        self.value = ""
        self.pins = [
            Pin( 1, "GND", "", "POWER"),
            Pin( 2, "VDD_SOC", "", "POWER"),
            Pin( 3, "VDD_HIGH", "", "POWER"),
            Pin( 4, "VDD_USB", "", "POWER"),
            Pin( 5, "GPIO1_IO00", "", "IO"),
            Pin( 6, "GPIO1_IO01", "", "IO"),
            Pin( 7, "GPIO1_IO02", "", "IO"),
            Pin( 8, "GPIO1_IO03", "", "IO"),
            Pin( 9, "GPIO1_IO04", "", "IO"),
            Pin(10, "GPIO1_IO05", "", "IO"),
            Pin(11, "GPIO1_IO06", "", "IO"),
            Pin(12, "GPIO1_IO07", "", "IO"),
            Pin(13, "GPIO1_IO08", "", "IO"),
            Pin(14, "GPIO1_IO09", "", "IO"),
            Pin(15, "GPIO1_IO10", "", "IO"),
            Pin(16, "GPIO1_IO11", "", "IO"),
            Pin(17, "GPIO1_IO12", "", "IO"),
            Pin(18, "GPIO1_IO13", "", "IO"),
            Pin(19, "GPIO1_IO14", "", "IO"),
            Pin(20, "GPIO1_IO15", "", "IO"),
            Pin(21, "GPIO1_IO16", "", "IO"),
            Pin(22, "GPIO1_IO17", "", "IO"),
            Pin(23, "GPIO1_IO18", "", "IO"),
            Pin(24, "GPIO1_IO19", "", "IO"),
            Pin(25, "GPIO1_IO20", "", "IO"),
            Pin(26, "GPIO1_IO21", "", "IO"),
            Pin(27, "GPIO1_IO22", "", "IO"),
            Pin(28, "GPIO1_IO23", "", "IO"),
            Pin(29, "GPIO1_IO24", "", "IO"),
            Pin(30, "GPIO1_IO25", "", "IO"),
            Pin(31, "GPIO1_IO26", "", "IO"),
            Pin(32, "GPIO1_IO27", "", "IO"),
            Pin(33, "GPIO1_IO28", "", "IO"),
            Pin(34, "GPIO1_IO29", "", "IO"),
            Pin(35, "GPIO1_IO30", "", "IO"),
            Pin(36, "GPIO1_IO31", "", "IO"),
            Pin(37, "GPIO2_IO00", "", "IO"),
            Pin(38, "GPIO2_IO01", "", "IO"),
            Pin(39, "GPIO2_IO02", "", "IO"),
            Pin(40, "GPIO2_IO03", "", "IO"),
            Pin(41, "GPIO2_IO04", "", "IO"),
            Pin(42, "GPIO2_IO05", "", "IO"),
            Pin(43, "GPIO2_IO06", "", "IO"),
            Pin(44, "GPIO2_IO07", "", "IO"),
            Pin(45, "GPIO2_IO08", "", "IO"),
            Pin(46, "GPIO2_IO09", "", "IO"),
            Pin(47, "GPIO2_IO10", "", "IO"),
            Pin(48, "GPIO2_IO11", "", "IO"),
            Pin(49, "GPIO2_IO12", "", "IO"),
            Pin(50, "GPIO2_IO13", "", "IO"),
            Pin(51, "GPIO2_IO14", "", "IO"),
            Pin(52, "GPIO2_IO15", "", "IO"),
            Pin(53, "GPIO2_IO16", "", "IO"),
            Pin(54, "GPIO2_IO17", "", "IO"),
            Pin(55, "GPIO2_IO18", "", "IO"),
            Pin(56, "GPIO2_IO19", "", "IO"),
            Pin(57, "GPIO2_IO20", "", "IO"),
            Pin(58, "GPIO2_IO21", "", "IO"),
            Pin(59, "GPIO2_IO22", "", "IO"),
            Pin(60, "GPIO2_IO23", "", "IO"),
            Pin(61, "GPIO2_IO24", "", "IO"),
            Pin(62, "GPIO2_IO25", "", "IO"),
            Pin(63, "GPIO2_IO26", "", "IO"),
            Pin(64, "GPIO2_IO27", "", "IO"),
            Pin(65, "GPIO2_IO28", "", "IO"),
            Pin(66, "GPIO2_IO29", "", "IO"),
            Pin(67, "GPIO2_IO30", "", "IO"),
            Pin(68, "GPIO2_IO31", "", "IO"),
            Pin(69, "USB_OTG1_DP", "", "USB"),
            Pin(70, "USB_OTG1_DN", "", "USB"),
            Pin(71, "USB_OTG1_VBUS", "", "POWER"),
            Pin(72, "USB_OTG1_ID", "", "USB"),
            Pin(73, "USB_OTG1_OC", "", "USB"),
            Pin(74, "XTALI", "", "SYSTEM"),
            Pin(75, "XTALO", "", "SYSTEM"),
            Pin(76, "VDD_SDIO", "", "POWER"),
            Pin(77, "SD1_CMD", "", "IO"),
            Pin(78, "SD1_CLK", "", "IO"),
            Pin(79, "SD1_DATA0", "", "IO"),
            Pin(80, "SD1_DATA1", "", "IO"),
            Pin(81, "SD1_DATA2", "", "IO"),
            Pin(82, "SD1_DATA3", "", "IO"),
            Pin(83, "ENET_MDIO", "", "IO"),
            Pin(84, "ENET_MDC", "", "IO"),
            Pin(85, "ENET_TX_DATA0", "", "IO"),
            Pin(86, "ENET_TX_DATA1", "", "IO"),
            Pin(87, "ENET_RX_DATA0", "", "IO"),
            Pin(88, "ENET_RX_DATA1", "", "IO"),
            Pin(89, "ENET_TX_EN", "", "IO"),
            Pin(90, "ENET_REF_CLK", "", "IO"),
            Pin(91, "ENET_RX_ER", "", "IO"),
            Pin(92, "ENET_RX_EN", "", "IO"),
            Pin(93, "ENET_TX_CLK", "", "IO"),
            Pin(94, "ENET_RX_CLK", "", "IO"),
            Pin(95, "RESET", "", "SYSTEM"),
            Pin(96, "BOOT_MODE0", "", "SYSTEM"),
            Pin(97, "BOOT_MODE1", "", "SYSTEM"),
            Pin(98, "BOOT_CFG0", "", "SYSTEM"),
            Pin(99, "BOOT_CFG1", "", "SYSTEM"),
            Pin(100, "BOOT_CFG2", "", "SYSTEM"),
        ]
